#!/bin/sh

COUNT=$1
USER_DATA=$2

aws ec2 run-instances \
  --image-id ami-3a511352 \
  --key-name ionblaster \
  --security-group-ids sg-24ff6941 \
  --instance-type m1.small \
  --enable-api-termination \
  --instance-initiated-shutdown-behavior terminate \
  --iam-instance-profile Arn=arn:aws:iam::698772785971:instance-profile/perf \
  --count $COUNT \
  --user-data file://$USER_DATA

