#!/bin/bash

curl -s -o /tmp/creds http://169.254.169.254/latest/meta-data/iam/security-credentials/perf
export aws_access_key_id=`cat /tmp/creds | jq -r ".AccessKeyId"`
export aws_secret_access_key=`cat /tmp/creds | jq -r ".SecretAccessKey"`
aws s3 cp s3://cavellc-perftest/metadata /tmp
source /tmp/metadata
docker login -e $DOCKER_EMAIL -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
docker run --net=host cavellc/cave-perftest:0.0.2 -DaccessKey=$PERFTEST_AK -DsecretKey=$PERFTEST_SK -DresultsDir=`date "+%Y-%m-%d-%H"`
shutdown -h now
